# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'runTimeLogUiUtilUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(953, 736)
        self.runLog_TE = QtWidgets.QTextEdit(Form)
        self.runLog_TE.setGeometry(QtCore.QRect(20, 370, 431, 311))
        self.runLog_TE.setObjectName("runLog_TE")
        self.exceptLog_TE = QtWidgets.QTextEdit(Form)
        self.exceptLog_TE.setGeometry(QtCore.QRect(470, 370, 451, 311))
        self.exceptLog_TE.setObjectName("exceptLog_TE")
        self.readRunLog_PB = QtWidgets.QPushButton(Form)
        self.readRunLog_PB.setGeometry(QtCore.QRect(300, 330, 151, 28))
        self.readRunLog_PB.setObjectName("readRunLog_PB")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 340, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(470, 340, 81, 16))
        self.label_2.setObjectName("label_2")
        self.readExceptLog_PB = QtWidgets.QPushButton(Form)
        self.readExceptLog_PB.setGeometry(QtCore.QRect(770, 330, 151, 28))
        self.readExceptLog_PB.setObjectName("readExceptLog_PB")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 20, 72, 15))
        self.label_3.setObjectName("label_3")
        self.readTempLog_PB = QtWidgets.QPushButton(Form)
        self.readTempLog_PB.setGeometry(QtCore.QRect(770, 10, 141, 28))
        self.readTempLog_PB.setObjectName("readTempLog_PB")
        self.tempLog_TE = QtWidgets.QTextEdit(Form)
        self.tempLog_TE.setGeometry(QtCore.QRect(20, 50, 901, 271))
        self.tempLog_TE.setObjectName("tempLog_TE")

        self.retranslateUi(Form)
        self.readRunLog_PB.clicked.connect(self.readRunLog)
        self.readExceptLog_PB.clicked.connect(self.readExceptLog)
        self.readTempLog_PB.clicked.connect(self.readTempLog)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.readRunLog_PB.setText(_translate("Form", "读取全部运行日志"))
        self.label.setText(_translate("Form", "运行日志"))
        self.label_2.setText(_translate("Form", "异常日志"))
        self.readExceptLog_PB.setText(_translate("Form", "读取全部异常日志"))
        self.label_3.setText(_translate("Form", "临时日志"))
        self.readTempLog_PB.setText(_translate("Form", "读取全部临时日志"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
