# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'runTimeLogUiUtilUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(763, 597)
        self.runLog_TE = QtWidgets.QTextEdit(Form)
        self.runLog_TE.setGeometry(QtCore.QRect(20, 40, 351, 541))
        self.runLog_TE.setObjectName("runLog_TE")
        self.exceptLog_TE = QtWidgets.QTextEdit(Form)
        self.exceptLog_TE.setGeometry(QtCore.QRect(380, 40, 351, 541))
        self.exceptLog_TE.setObjectName("exceptLog_TE")
        self.readRunLog_PB = QtWidgets.QPushButton(Form)
        self.readRunLog_PB.setGeometry(QtCore.QRect(220, 10, 151, 28))
        self.readRunLog_PB.setObjectName("readRunLog_PB")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 10, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(380, 10, 81, 16))
        self.label_2.setObjectName("label_2")
        self.readExceptLog_PB = QtWidgets.QPushButton(Form)
        self.readExceptLog_PB.setGeometry(QtCore.QRect(580, 10, 151, 28))
        self.readExceptLog_PB.setObjectName("readExceptLog_PB")

        self.retranslateUi(Form)
        self.readRunLog_PB.clicked.connect(self.readRunLog)
        self.readExceptLog_PB.clicked.connect(self.readExceptLog)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.readRunLog_PB.setText(_translate("Form", "读取全部运行日志"))
        self.label.setText(_translate("Form", "运行日志"))
        self.label_2.setText(_translate("Form", "异常日志"))
        self.readExceptLog_PB.setText(_translate("Form", "读取全部异常日志"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
